### ISSUE TITLE
produce multi-targeted package

### ISSUE THREAD

**Issue by clifton-collins3iii** [SoftCircuits/IniFileParser#2]
modify test project to produce:  <TargetFrameworks>net45;net452;net46;netcoreapp2.1</TargetFrameworks>
modify output project to produce: <TargetFrameworks>netstandard2.0;net40;net45;net452;net46;netcoreapp2.1</TargetFrameworks>

**Comment by clifton-collins3iii** [comment]
@SoftCircuits see forked branch for proposed change.
https://github.com/clifton-collins3iii/IniFileParser/tree/multiframework-targeting

**Comment by SoftCircuits** [comment]
Can you explain the point of this? Most of these platforms support .NET Standard.

**Comment by clifton-collins3iii** [comment]
The nuget package refused to install on a winform app targeted at .net
4.5.2, stating no supported target, until I added them into the ask project.

Clifton Collins
225-788-0355
semper quaeritis illi

**Comment by SoftCircuits** [comment]
@clifton-collins3iii Just curious, did you try changing to .NET 4.7 or later?

**Comment by clifton-collins3iii** [comment]
I changed two projects from 4.5.2 to 4.7 and then to 4.7.2 and was able to
install the nuget package.
Clifton G. Collins III
225-788-0355
semper quaeritis illi


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
