### ISSUE TITLE
Using a quoted string in values

### ISSUE THREAD

**Issue by lmattcris** [SoftCircuits/IniFileParser#4]
I see that with a key's value as in
```
[Section]
Key="My value"
```
the GetSetting property obtains a string like
`"\"My value\""`
not interpreting the quotes as... quotes 😄 

I also see that quotes aren't necessary for embedded spaces, but is there any option to **force** using quotes in strings when there are blanks? Hence, automatically removing the quotes

**Comment by SoftCircuits** [comment]
There is no option for this. I have never seen quotes be part of the INI file standard. Unlike with CSV files, I don't see why they would be necessary. Who is writing INI files that way?

If you can show me where this is standard, I'll consider adding support for it.

Meanwhile, you can remove those quotes using `value = value.Trim('"")`.

**Comment by lmattcris** [comment]
Well, the INI files format is indeed a loose one. I've been using for a long time the GetPrivateProfileString API call, from Win32, and I had to replicate it in different environments. It uses both single and double quotes escaping in values.
[https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestringw](url)
It's also mentioned on Wikipedia as well (as shown in an example too)
[https://en.wikipedia.org/wiki/INI_file#Comparison_of_INI_parsers](url)

I think that sometimes it can be a help in reading complex assignments, like
`MyHideouslyLongNameKey = "= This is going to be cleaner than without blanks around ="`

Just a welcome feature, not an _issue_ - sorry if I used the "issue" space on GitHub! 😺

**Comment by SoftCircuits** [comment]
So, your first link talks about supporting quotes around the key.

```
[Section]
"Key"=My Value
```

This would actually be necessary if you needed an equal sign in the key. I might consider this. But it's different from what you need.

I couldn't find where the Wikipedia article talked about quoted values.

**Comment by lmattcris** [comment]
Oh, I think their text is a bit convoluted, but when they write 

> If the string associated with lpKeyName is enclosed in single or double quotation marks, the marks are discarded when the GetPrivateProfileString function retrieves the string

it refers to the **value** string to be assigned... I hope
I've never seen key names with spaces in between, while I've seen quite often values quoted, as in the Wikipedia example at the link above

**Comment by SoftCircuits** [comment]
I'm closing this issue for now. I don't see anyone else needing this and removing quotes now could potentially break existing code that expects quotes to be left in.

Feel free to reach out if you can think of any other arguments for making a change here.
