### ISSUE TITLE
Invalid ini read and write

### ISSUE THREAD

**Issue by UnrealKaraulov** [SoftCircuits/IniFileParser#6]
After write

```
[test]
value = value
```

saved as

```
[test]
value= value
```

This is very bad!

And when read, i got spaces in value

```
[test]
value = value
```

Loaded as ' value' instead of 'value'

This is bad too

**Comment by SoftCircuits** [comment]
This logic is well tested and does not behave as you seem to be describing.

You're going to need to show your code. How did you write the first example. There should never be a space after the equal sign unless your value starts with a space.

If you're read an INI file created by other software, that other software is not working right and you'll need to trim spaces off the value.
